#!/usr/bin/with-contenv bash

# RUN chown -R abc:abc $HOME
sudo -i -u abc bash << EOF
code-server --user-data-dir /config/data --extensions-dir /config/extensions --disable-telemetry --install-extension esbenp.prettier-vscode
code-server --user-data-dir /config/data --extensions-dir /config/extensions --disable-telemetry --install-extension golang.go
EOF


if [ -f "$HOME/.zshrc" ]; then
    sudo -i -u abc bash << EOF
        git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME pull
EOF
else
    sudo sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    rm -rf "$HOME/.zshrc"
    sudo -i -u abc bash << EOF
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
        bash -c 'source $HOME/.nvm/nvm.sh && nvm install node'

        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        git clone --bare https://github.com/abibby/dotfiles.git $HOME/.dotfiles
        git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
EOF
fi